==  Sterilisation

> Sterilisation heißt Abtöten oder Entfernen der an Stoffen,
> Zubereitungen und an Gegenständen vorkommenden
> lebensgefährlichen Formen von Mikrooorganismen. Als
> steril dürfen Stoffe, Zubereitungen und Gegenstände
> nur dann bezeichnet werden, wenn  sie frei von lebensfähigen Formen
> von Mikroorganismen, die unter den Züchtungsbedingungen einer Prüfung für steril nachgewiesen
> werden können.
>
> -- Lehrbuch der pharmazeutischen Technologie; R. Voigt, Verlag Volk und Gesundheit Berlin 1979

Arzneimittel, die nur durch  Keimabtrennung (Sterilfiltration) "sterilisiert" wurden, dürfen nicht als
pass:[<u>steril</u>] sondern nur als pass:[<u>aseptisch</u>] hergestellt, bezeichnet werden. Bei der
Sterilisation werden drei Methoden unterschieden:

. die chemische Sterilisation
. die physikalische Sterilisation
. die Strahlensterilisation

Weiterhin unterscheidet man noch, Sterilisation durch Keimabtötung und Sterilisation durch Keimabtrennung. Wobei
man hier jedoch keine scharfen Grenzen ziehen kann,
da es auch viele Sterilisationsmethoden gibt,
die sowohl durch Keimabtötung als auch Keimabtrennung den
betroffenden Stoff sterilisieren, so dass hier ein fließender Übergang von einer Sterilisationsmethode
zur anderen erkennbar ist.

=== Chemische Sterilisation

Die chemische Sterilisation beruht sowohl auf dem Einsatz
von Gasen, als auch von Flüssigkeiten. Sie führt zu
einer Denaturalisierung der Eiwißstruktur der Mikroorganismen.
Das heißt, in den meisten Fällen lagert sich ein Radikal durch vorheriges Lösen einer Doppelbindung
an das Eiweißmolekül an. Es entsteht somit ein
völlig neues Eiweiß mit neuer Struktur und neuen Eigenschaften.
Die Mikroorganismen sind dann nicht mehr lebensfähig.
Der Sterilisierungserfolg hängt von vielen schwerüberschaubaren Faktoren ab, wie zum Beispiel
Art und Ausgangskonzentration der Keime, Temperatur, Feuchtigkeit,
Gaskonzentration und Gasdruck.

Entscheidende Bedeutung für die Keimabtötungsrate ist
das Eindringvermögen (Diffusionsvermögen) des Sterilisationsmittels
in das zu sterilisierende Material.
Das Leutoxieren von Sbstanzen mit Äthylenoxid ist die
häufigste Form der Gassterilisisation im pharmazeutischen Bereich.
So word auch in der PA  Bereich Antibiotika
dieses Verfahren angewendet. Die Leutoxierung wird im
aseptischen Bereich aber getrennt von der Abfülleinheit
durchgeführt. Bei der Arbeit mit Äthylenoxid gelten
besondere Arbeits- und Brandschutzbestimmungen. Da es
sich hier um ein Gift der Abteilung 1 handelt, welches
bei einer Konzentration von 100-200 mg/l Atemluft auf
den Menschen tödlich wirkt, dürfen beim Sterilisationsvorgang
keine Personen im Rauzm sein. Äthylenoxid ist
ein loses sehr reationsfreudiges Gas, das mit Luft
in Konzentraionen ab 3 Vol. % explosive Gemische bildet.

Durch diese Verbindung werden die Atemwege gereizt und
in höheren Konzentrationen treten Übelkeit, Kpfschmerzen
und Erbrechen auf. Zur Sterilisation werden Äthylenoxid-CO~2~ Gemische
eingesetzt. Die gebäuchliste Mischung
besteht aus 90 Vo. % Äthylenoxid und 10% CO~2~. In
Konzentrationen zwischen 800 bis 1500 mg/l wirkt
Äthylenoxid tödlich auf Bakterien, Pilze, Viren und
auch auf Sporen. Eine optimale Abtötungsrate wird bei
20 - 40%  nach anderen Angaben mindestens 50% relative
Feuchte zwischen 20°C - 70°C erreicht. Durch Temperatur-
und Druckerhöhung kann der Abtötungseffekt noch erhöht
werden. Die Begasung der zu sterilisierenden Substanz
mit Äthylenoxid erfolgt im Küppermischer unter 0,5 atü.
Die Substanz wird mindestens 7 Stunden begast. Nach der
Sterilisation werden verbleibende Äthylenreste durch
Einblasen keimfiltrierter Luft ausgetrieben.
Anschließend muß das sterile Gut gelagert werden.

Eine weitere chemische Sterilisationsmethode ist das Foralinisieren.
Bei der Sterilisation mittels Formalin
gibt es zwei Methoden. Die erste nutzt Formaldehyddämpfe
und die zweite die Formaldehydlösung zur Keimabtötung.
Beide Setilisationsarten werden in der aseptischen Abfülleinheit durchgeführt.
Bei der Gassterilisation
mittels Formalin werden nach Schtende, wenn sich
keine Personen mehr im aseptischen Bereich aufhalten,
Formaldehyddämpfe in den Raum geblasen. Das geschieht,
indem 90 Minuten Formaldehyddämpfe durch die Belüftungsanlage
geschickt werden.

In dieser Zeit werden die regativen Formen der Mikroorganismen in der luft abgetötet.
Die Belüftungsanlage
bleibt nach der Sterilisation weiterhin in Betrieb.
Laut Lieeratur (Mikrobilogisches Praktikum; Helga Schröder, Volk und Wissen Berlin 1980) wird die
Formalinisierung als Desinfektion bezeichnet. (Seite 34
"Desinfektion der Raumluft") Jedoch im Artikel über die chemische Sterilisation im "Lehrbuch der pharmazeutischen
Technologie" (3. Auflage, Verlag Volk und Wissen Berlin 1979, Seite 611, 3. Absatz) wird die  Formalinisierung
als Sterilisationsmethode erwähnt. In der Abteilung PA5 Bereich Antibiotika wird weiterhin die Sterilisation
durch Alkohol angewandt. Verwendet wird hierbei 70%iges
Äthanol. Um der Entfettung der Haut vorzubeugen, werden dem Äthanol 1% Glyzerin zugegeben. Es wirkt wasserentziehend
und dadurch stark schädigend auf den Mikroorganismus. Vegetative Keime sterben in 0,5 min ab,
Sporen benötigen längere Einwirkzeit. Die Methode wird
überall da angewandt, wo kurze Einwirkzeit, geringe Mengen
und nach kurzter Zeit wieder Trockenheit herrschen muß.
Zum Beispiel werden Wände, Maschinen und Arbeitsflächen
mit Alkohol gereinigt. Da der Alkohol schnell verdunstet,
sind die sterilisierten Flächen nie lange feucht und gleichzeitig
werden auch noch Keime der Lauft abgetötet.
Deshalb bildet Alkohol ein vorzügliches Sterilisationsmittel.

=== Physikalische Sterilisation

Die physikalische Sterilisation beruht vorwiegend auf der
Einwirkung von Hitze auf die Mikroorganismen. Sie
kann deshalb nicht bei temperaturempfindlichen Substanzen eingesetzt werden.
In der Antibiotika Abteilung wird
zum einen die Heißluftsterilisation und zum anderen die Dampfsterilisation eingesetzt.

Bei der Heißluftsterilisation können Materialien wie
Glas, Porzellan und Metallgegenstände sterilisiert werden.
Im Sterilisierungstunnel werden gerinigte Glasflaschen
aus dem Spülraum sterilisiert und in den aseptischen
Abfüllbereich eingeschlust. Nach der Aufgabe der Flaschen
passieren diese die Einlaufzone des Tunnels. Dort werden
sie vom Förderband weitertranportiert zur Trockenzone.
Diese Zone dient zum Trockenen der Injektionsflaschen.
Infrarotquarzglasstrahler dienen als Heizquelle. Danach
passieren die Flaschen die Sterilisationszone. Diese
durchlaufen sie 20 Minuten bei einer Temperatur von 280°C.
Auch hier werden als Heizquelle Infrarotqurzglasstrahler
eingesetzt. Diese Strahler besitzen vergoldete Reflektoren.
Durch diese wird die Wärmestrahlung gerichtet, um eine
optimale Ausbeute zu erzielen. Es folgt dann die Kühlzone
umd die Auslaufzone. Durch Vorfilter und eine Hosch-Filter
(Hochleistungsschwebestofffilter) - Dusche wird nach
dem Laminar-flow-Prinzip ein senkrecht nach unten gerichteter
Frischluftstrom geringer Geschwindigkeit erzeugt. Dieser
bewegt sich durch das Transportband hindurch und wird
unterhalb von einem Abluftkanal nach außen abgeführt.
Somit erreicht man eine partikelarme Atmosphäre im Berich
des gerinigten und sterilisierten Gutes. Die steril-filtrierte Luft
aus der Kühlzone wird weiterhin durch die
Gebläse zur Luftschleuse in die Einlaufzone geführt.
Eine weitere Form der Sterilisation ist die Dampfsterilisation.
Bei der Dampsterilisation kommt gespannter,
gesättigter und im allgemeinen luftfreier Wasserdampf
zur Anwendung. Das heißt ein Dampf von etwa 120°C bei
einem Druck von 0,2 MPa, der mit Wasser unmittelbar
in Berührung steht. Diese Sterilisation wird in
Autoklaven durchgeführt. Beim Anheizen bleibt das Dampfventil
geöffnet, so kann die gesamte Luft entweichen
und nach dem Schließen liegt dann ein luftfreier Dampf
vor. Die Entfernung der Luft ist notwendig, da der
Dampf nicht nur als Wärmeüberträger dient, sondern
sein Kondensat auch in die Poren des Stoffes eindringt.
Dampf und Kondensat üben hierbei eine direkte keimtötende
Wirkung aus, die bei Luftanwesenheit gemindert
werden würde. Außerdem ist die Luft ein schlechter Wärmeleiter
und es könnten sich "Kälteinseln" bilden.
Durch die Wirkung des Wasserdampfes wird zunächst
die Zellwand der Mikroorganismen aufgelockert, danach
kann dann die Hitze direkt auf die Kernsubstanz einwirken
und sie zuerstören. Bei der Dampfsterilisation
werden bereits nach 8 Minuten sogar Sporen sicher
zerstört. Im Sterilisator befinden sich Sporenerdepäckchen
an verschiedenen Meßorten, die nach der Autoklavierung
auf Sterilistät geprüft werden.

=== Strahlensterilisation

