==  Sterilisation

> Sterilisation heißt Abtöten oder Entfernen der an Stoffen,
> Zubereitungen und an Gegenständen vorkommenden
> lebensgefährlichen Formen von Mikrooorganismen. Als
> steril dürfen Stoffe, Zubereitungen und Gegenstände
> nur dann bezeichnet werden, wenn  sie frei von lebensfähigen Formen
> von Mikroorganismen, die unter den Züchtungsbedingungen einer Prüfung für steril nachgewiesen
> werden können.
>
> -- Lehrbuch der pharmazeutischen Technologie; R. Voigt, Verlag Volk und Gesundheit Berlin 1979

Arzneimittel, die nur durch  Keimabtrennung (Sterilfiltration) "sterilisiert" wurden, dürfen nicht als
pass:[<u>steril</u>] sondern nur als pass:[<u>aseptisch</u>] hergestellt, bezeichnet werden. Bei der
Sterilisation werden drei Methoden unterschieden:

. die chemische Sterilisation
. die physikalische Sterilisation
. die Strahlensterilisation

Weiterhin unterscheidet man noch, Sterilisation durch Keimabtötung und Sterilisation durch Keimabtrennung. Wobei
man hier jedoch keine scharfen Grenzen ziehen kann,
da es auch viele Sterilisationsmethoden gibt,
die sowohl durch Keimabtötung als auch Keimabtrennung den
betroffenden Stoff sterilisieren, so dass hier ein fließender Übergang von einer Sterilisationsmethode
zur anderen erkennbar ist.

=== Chemische Sterilisation

Die chemische Sterilisation beruht sowohl auf dem Einsatz
von Gasen, als auch von Flüssigkeiten. Sie führt zu
einer Denaturalisierung der Eiwißstruktur der Mikroorganismen.
Das heißt, in den meisten Fällen lagert sich ein Radikal durch vorheriges Lösen einer Doppelbindung
an das Eiweißmolekül an. Es entsteht somit ein
völlig neues Eiweiß mit neuer Struktur und neuen Eigenschaften.
Die Mikroorganismen sind dann nicht mehr lebensfähig.
Der Sterilisierungserfolg hängt von vielen schwerüberschaubaren Faktoren ab, wie zum Beispiel
Art und Ausgangskonzentration der Keime, Temperatur, Feuchtigkeit,
Gaskonzentration und Gasdruck.

Entscheidende Bedeutung für die Keimabtötungsrate ist
das Eindringvermögen (Diffusionsvermögen) des Sterilisationsmittels
in das zu sterilisierende Material.
Das Leutoxieren von Sbstanzen mit Äthylenoxid ist die
häufigste Form der Gassterilisisation im pharmazeutischen Bereich.
So word auch in der PA  Bereich Antibiotika
dieses Verfahren angewendet. Die Leutoxierung wird im
aseptischen Bereich aber getrennt von der Abfülleinheit
durchgeführt. Bei der Arbeit mit Äthylenoxid gelten
besondere Arbeits- und Brandschutzbestimmungen. Da es
sich hier um ein Gift der Abteilung 1 handelt, welches
bei einer Konzentration von 100-200 mg/l Atemluft auf
den Menschen tödlich wirkt, dürfen beim Sterilisationsvorgang
keine Personen im Rauzm sein. Äthylenoxid ist
ein loses sehr reationsfreudiges Gas, das mit Luft
in Konzentraionen ab 3 Vol. % explosive Gemische bildet.

Durch diese Verbindung werden die Atemwege gereizt und
in höheren Konzentrationen treten Übelkeit, Kpfschmerzen
und Erbrechen auf. Zur Sterilisation werden Äthylenoxid-CO~2~ Gemische
eingesetzt. Die gebäuchliste Mischung
besteht aus 90 Vo. % Äthylenoxid und 10% CO~2~. In
Konzentrationen zwischen 800 bis 1500 mg/l wirkt
Äthylenoxid tödlich auf Bakterien, Pilze, Viren und
auch auf Sporen. Eine optimale Abtötungsrate wird bei
20 - 40%  nach anderen Angaben mindestens 50% relative
Feuchte zwischen 20°C - 70°C erreicht. Durch Temperatur-
und Druckerhöhung kann der Abtötungseffekt noch erhöht
werden. Die Begasung der zu sterilisierenden Substanz
mit Äthylenoxid erfolgt im Küppermischer unter 0,5 atü.
Die Substanz wird mindestens 7 Stunden begast. Nach der
Sterilisation werden verbleibende Äthylenreste durch
Einblasen keimfiltrierter Luft ausgetrieben.
Anschließend muß das sterile Gut gelagert werden.

Eine weitere chemische Sterilisationsmethode ist das Foralinisieren.
Bei der Sterilisation mittels Formalin
gibt es zwei Methoden. Die erste nutzt Formaldehyddämpfe
und die zweite die Formaldehydlösung zur Keimabtötung.
Beide Setilisationsarten werden in der aseptischen Abfülleinheit durchgeführt.
Bei der Gassterilisation
mittels Formalin werden nach Schtende, wenn sich
keine Personen mehr im aseptischen Bereich aufhalten,
Formaldehyddämpfe in den Raum geblasen. Das geschieht,
indem 90 Minuten Formaldehyddämpfe durch die Belüftungsanlage
geschickt werden.

In dieser Zeit werden die regativen Formen der Mikroorganismen in der luft abgetötet.
Die Belüftungsanlage
bleibt nach der Sterilisation weiterhin in Betrieb.
Laut Lieeratur (Mikrobilogisches Praktikum; Helga Schröder, Volk und Wissen Berlin 1980) wird die
Formalinisierung als Desinfektion bezeichnet. (Seite 34
"Desinfektion der Raumluft") Jedoch im Artikel über die chemische Sterilisation im "Lehrbuch der pharmazeutischen
Technologie" (3. Auflage, Verlag Volk und Wissen Berlin 1979, Seite 611, 3. Absatz) wird die  Formalinisierung
als Sterilisationsmethode erwähnt. In der Abteilung PA5 Bereich Antibiotika wird weiterhin die Sterilisation
durch Alkohol angewandt. Verwendet wird hierbei 70%iges
Äthanol. Um der Entfettung der Haut vorzubeugen, werden dem Äthanol 1% Glyzerin zugegeben. Es wirkt wasserentziehend
und dadurch stark schädigend auf den Mikroorganismus. Vegetative Keime sterben in 0,5 min ab,
Sporen benötigen längere Einwirkzeit. Die Methode wird
überall da angewandt, wo kurze Einwirkzeit, geringe Mengen
und nach kurzter Zeit wieder Trockenheit herrschen muß.
Zum Beispiel werden Wände, Maschinen und Arbeitsflächen
mit Alkohol gereinigt. Da der Alkohol schnell verdunstet,
sind die sterilisierten Flächen nie lange feucht und gleichzeitig
werden auch noch Keime der Lauft abgetötet.
Deshalb bildet Alkohol ein vorzügliches Sterilisationsmittel.





=== Physikalische Sterilisation
=== Strahlensterilisation