== Zur Einhaltung der RHR Richtlinien im Bereich Antibiotika

In der DDR sind Normen für die mikrobilogische Reinheit von Arzneimitteln mit dem 1977 erfolgten Inkrafttreten des Arzneibuches der DDR verbindlich geworden. 
Beratungen über die Ausarbeitung einer Rahmen-Hygiene-Richtlinie für die Produktion von Arzneimitteln und Gesundheitspflegemitteln begannen in der DDR im Jahr 1973.
Die zur Zeit bestehende Fassung der Rahmenhygieneordnung besitzt noch keine gesetzliche Verbindlichkeit, sondern sie stellt lediglich eine Empfehlung dar. 
Aus den RHR ergeben sich folgnde Kriterien:

1. Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial
2. Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen
3. Richtlinien für die entsprechenden Produktionsräume
4. Richtlinien für Ausrüstung und Verfahren
5. Richtlinien für Personen, die in diesem Bereich der Herstellung von Antibiotika arbeiten
6. Richtlinien für betriebliche Kontrollen durch verschiedene Verfahren

=== Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial

Hierunter ist die mikrobiologische Reinheit der Ausgangsstoffe zu verstehen.  Der Hersteller von Arzeneimitteln ist verpflichtet, sich bei den Herstellern bzw. Lieferanten der Ausgangsstoffe über bereits durchgführte Maßnahmen dieser Art zu informieren. Der Lieferant ist gleichzeitig verpflichtet, eine entsprechende Dokumentation zu übergeben. 

Das Verpackungsmaterial muß so beschaffen sein, daß eine Kontaminiation der Ausgangsstoffe vermieden wird. 
Sind die Verpackungen der Ausgangsstoffe beschädigt, verschmutzt oder durchfeuchtet, so werden die Ausgangsstoffe gegebenenfalls von der Verwendung ausgeschlossen.
Müssen Ausgangsstoffe umgefüllt werden, darf deren Reinheitsgrad dabei nicht beeinträchtigt werden. Die Lagerung der Ausgangsstoffe darf nur in Räumen erfolgen, die 
in ordentlichen und sauberem Zustand sind. Über die notwendigen Reinigungsmaßnahmen ist ein Nachweis zu führen. Die zur Lagerung benutzten Räume dürfen nicht für andere, produktionsfremde Zwecke genutzt werden und es dürfen keine Durchgangsräume sein. 
Die Ausgangsstoffe müssen nach den jeweils gültigen TGL angegebenen Aufbewahrungsbedingungen gelagert werden. Dabei muß die Raumtemperatur und Luftfreuchtigkeit der Lagerräume täglich kontrolliert und registriert werden. Die Stabilität der Ausgangsstoffe darf durch die Lagerung nicht beeinträchtigt werden. 

=== Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen

Hinsichtlich des erfoderlichen Reinheitsgrades der Produktionsräume werden die Reinheitsstufen 1 bis 4 unterschieden. 
Die Reinheitsstufen der Räume werden durch unterschiedliche Farbgebung deutlich sichtbar gekennzeichnet:

"Reinheitsstufe 1a" und "Reinheitsstufe 1b":: rot gekennzeichnet
"Reinheitsstufe 2":: blau gekennzeichnet
"Reinheitsstufe 3":: grün gekennzeichnet
"Reinheitsstufe 4":: gelb gekennzeichnet

Diese Sicherheitsfarben erfolgen nach TGL - Normen. 

=== Richtlinien für die entsprechenden Produktionsräume

Abgesehen von den bereits genannten Bestimmungen für die Kennzeichnung der Produktionsräume durch Sicherheitsfarben sind weitere Kriterien zu beachten. Auf einige der wichtigsten will ich in meinen Ausführungen eingehen.

Der Reinheitsgrad von Personen und Materialien ist durch das Passieren von Schleusen von einer geringeren in die jeweils erforderliche höhere Reinheitsstufe zu heben.
Dabei sind für Produktionsräume mit Reinheitsstufen 1b - 3 voneinander getrennte Personen- und Materialschleusen erforderlich. Bei den Personenschleusen unterscheiden wir je nach Reinheitsstufen Doppelschleusen und Einfachschleusen. 

Doppelschleusen werden vor Produktionsräumen der Reinheitsstufen 1b und 2 benutzt. Sie bestehen aus einer Vorschleuse und einer Sterilschleuse. In der Vorschleuse wird die Wegekleidung abgelegt und in der Sterilschleuse,
die Sterilkleidung angelegt. In der jeweiligen Schleuse müssen Aufbewahrungsmöglichkeiten für die Bekleidungen sein. Außerdem muß die Möglichkeit der gründlichen Reinigung und Desinfektion der Hände und Unterarme bestehen. Vor Produktionsräumen der Reinheitsstufe 3 sind Einfachschleusen vorhanden. Hier wird die Wegekleidung abgelegt und die Hygienekleidung angelegt.

Materialien, die in die Produktionsräume einzuschleusen sind, werden durch Materialschleusen befördert. Hier wird durch geeignete Methoden, die hygienische Reinigung durchgeführt, zum Beispiel durch Entfernung des Verpackungsmaterials, der Desinfektion der Verpackung, durch Besprühen, Begasung oder durch UV-Strahler. 

Weitere Anforderungen, die an Produktionsräume für Antibiotika gestellt werden:

- Die Räume müssen in sauberem und ordentlichen Zustand gehalten werden. Sie müssen in ihrer Größe eine entsprechende Reinigung und Wartung der Maschinen zulassen.
- Das Aufbewahren von persönlichen Gegenständen sowie das Halten von Zimmerpflanzen und Tieren ist nicht zulässig.
- Wände, Decken und Fußböden sowie Arbeitsflächen müssen eine glatte Oberfläche aufweisen und für Desinfektionsmittel geeignet sein, je nach Reinheitsstufen gelten noch spezielle Hinweise. 
- Abflußwasser müssen ungehindert abfließen können und eine Desinfektion möglich sein
- je nach Reinheitsstufen müssen die Türen und Fenster dicht verschließbar sein und während des Produktionsprozesses geschlossen gehalten werden.
- Belüftungs- und Klimaanlagen müssen eine gute Luftzirkulation aufweisen und vermeiden das Verunreinigungen der Produktionsräume auftreten
- Räume für mit Staubentwicklung verbundenen Arbeiten müssen eine wirksame Absaugvorrichtung haben
- je nach Reinheitsstufen ist auf entsprechende Temperaturen und Einhaltung der relativen Luftfeutigkeit zu achten
- die zum Waschen und Desinfizieren der Hände benötigten Wasserhähne müssen in den Produktionsräumen mit Arm- und Fußhebel bedienbar sein.
- Toiletten dürfen keinen direkten Zugang zu den Produktionsräumen haben
- die Säuberung der Produktionsräume und der sanitären Einrichtungen sind nach betrieblichen Arbeitsvorschriften regelmäßig durchzuführen; über die Art der verwendeten Desinfektionsmittel ist ein schriftlicher Nachweis zu führen

=== Richtlinien für Ausrüstung und Verfahren

Durch geeignete Ausrüstung und Verfahren ist zu gewährleisten, daß eine Kontamination der Produkte vermieden wird. Ebenfalls muß die Vermehrung der eventuell in den Ausgangsstoffen enthaltenen mikrobiellen Verunreinigungen verhindert werden oder eine Reduktion der Keimzahl erfolgen. Der Herstellungsprozeß ist möglichst geschlossen zu halten und die für das Wachstum von Mikroorganismen günstigen Bedingungen zu vermeiden. 

Beim Wägen der Ausgangsstoffe darf keine Beeinträchtigung der Reinheit erfolgen, Die Maschinen und Geräte, die beim Herstellungsprozeß benötigt werden, müssen regelmäßig nach betrieblichen Vorschriften gereinigt, desinfiziert oder sterilisiert werden. Dabei müssen die Vorschriften dazu am Arbeitsplatz vorliegen. Auch die Aufbewahrung von Halbfertigprodukten hat so zu erfolgen,
daß keine Beeinträchtigung ihrer Reinheit zustande kommt.

=== Richtlinien für Personen, die in diesem Bereich der Herstellung von Antibiotika arbeiten

Alle Personen, die mit der Herstellung von Arzneimitteln  beschäftigt  sind, unterliegen den Festlegungen der 13. Durchführungsbestimmung zum Arzneimittelgesetz.
Ferner sind folgende Richtlinien für beschäftigte Personen in der Antibiotikaherstellung maßgebend:

- achten auf persönliche Hygiene
- Händereinigung und Händedesinfektion je nach Reinheitsstufen und nach verschiedenen Methoden
- Art der Kleidung und die Häufigkeit des Wechselns der Kleidung richtet sich je nach den Reinheitsstufen der Produktionsräume
- Die Häufigkeit der Desinfektion mit Formaldehydlösung richtet sich ebenfalls nach den Reinheeitsstufen, in denen die Personen arbeiten
- Die Art des Kopf- und Mundschutzes, sowie dessen Wechsel richtet sich je nach Reinheitsgesetz des Produktionsraumes
- Handschue müssen sterilisiert bzw. desinfiziert sein und aus Gummi bestehen
- Grundsätzlich ist die Arbeitskleidung von der Straßenkleidung getrennt aufzubewahren.
- Essen, Trinken und Rauchen kann in den Produktionsräumen nicht gestattet werden. 

=== Richtlinien für betriebliche Kontrollen durch verschiedene Verfahren

Kontrollen werden nach betrieblich festgelegten Plänen durchgefürt. Die Ergebnisse der Kontrollen müssen dokumentiert werden und so lange aufbewahrt werden, bis die Verwendbarkeitsdauer der kontrollierten Stoffe abgelaufen ist. 

Es werden folgende Kontrollen durchgeführt:

==== Kontrolle zur Prüfung der Produktionsbedingungen

In diesen Kontrollen werden bei den einzelnen Herstellungsschritten in geeigneter Weise Proben entnommen. Diese werden in Abhängigkeit von der Art des Produkts auf folgendes geprüft:

- Prüfung auf mikrobiologische Reinheit
- Prüfung auf Sterilität
- Prüfung auf pyrogene Verunreinigungen und Prüfung auf Abwesenheit von Salmonellen-Arten in Rohstoffen tierischer Herkunft


==== Kontrolle der Reinigungs- und Desinfektionsmaßnahmen

Hierbei werden von Maschinen, Geräten, Arbeitsflächen und manchmal auch Fußböden Abklatch-Proben für den Keimnachweis entnommen. 

==== Kontrolle für die in der Produktion angewendeten Sterilisationsverfahren

Dabei sollen nicht nur die Sterilisationsapparaturen, sondern auch die Geräte zur bakterienfreien Filtration kontrolliert werden.

==== Kontrolle des Keimgehalts der Luft

==== Laminar- Flow- und Sterilbelüftungseinheiten sind auf Funktionstüchtigkeit zu prüfen

==== Kontrolle der Händedesinfektion

Hierbei werden die Hände bzw. die Fingerkuppen auf Kulturmedien gedrückt. Nach Bebrutung erfolgt die Auszählung der Mikroorganismenkolonien. 

Für die Kontrollen der Einhaltung der RHR ist die TKO bzw. die Abteilung Qualitätssicherung verantwortlich.



