== Zur Einhaltung der RHR Richtlinien im Bereich Antibiotika

In der DDR sind Normen für die mikrobilogische Reinheit von Arzneimitteln mit dem 1977 erfolgten Inkrafttreten des Arzneibuches der DDR verbindlich geworden. 
Beratungen über die Ausarbeitung einer Rahmen-Hygiene-Richtlinie für die Produktion von Arzneimitteln und Gesundheitspflegemitteln begannen in der DDR im Jahr 1973.
Die zur Zeit bestehende Fassung der Rahmenhygieneordnung besitzt noch keine gesetzliche Verbindlichkeit, sondern sie stellt lediglich eine Empfehlung dar. 
Aus den RHR ergeben sich folgnde Kriterien:

1. Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial
2. Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen
3. Richtlinien für die entsprechenden Produktionsräume
4. Richtlinien für Ausrüstung und Verfahren
5. Richtlinien für Personen, die in diesem Bereich der Herstellung von Antibiotika arbeiten
6. Richtlinien für betriebliche Kontrollen durch verschiedene Verfahren

=== Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial


