== Zur Einhaltung der RHR Richtlinien im Bereich Antibiotika

In der DDR sind Normen für die mikrobilogische Reinheit von Arzneimitteln mit dem 1977 erfolgten Inkrafttreten des Arzneibuches der DDR verbindlich geworden. 
Beratungen über die Ausarbeitung einer Rahmen-Hygiene-Richtlinie für die Produktion von Arzneimitteln und Gesundheitspflegemitteln begannen in der DDR im Jahr 1973.
Die zur Zeit bestehende Fassung der Rahmenhygieneordnung besitzt noch keine gesetzliche Verbindlichkeit, sondern sie stellt lediglich eine Empfehlung dar. 
Aus den RHR ergeben sich folgnde Kriterien:

1. Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial
2. Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen
3. Richtlinien für die entsprechenden Produktionsräume
4. Richtlinien für Ausrüstung und Verfahren
5. Richtlinien für Personen, die in diesem Bereich der Herstellung von Antibiotika arbeiten
6. Richtlinien für betriebliche Kontrollen durch verschiedene Verfahren

=== Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial

Hierunter ist die mikrobiologische Reinheit der Ausgangsstoffe zu verstehen.  Der Hersteller von Arzeneimitteln ist verpflichtet, sich bei den Herstellern bzw. Lieferanten der Ausgangsstoffe über bereits durchgführte Maßnahmen dieser Art zu informieren. Der Lieferant ist gleichzeitig verpflichtet, eine entsprechende Dokumentation zu übergeben. 

Das Verpackungsmaterial muß so beschaffen sein, daß eine Kontaminiation der Ausgangsstoffe vermieden wird. 
Sind die Verpackungen der Ausgangsstoffe beschädigt, verschmutzt oder durchfeuchtet, so werden die Ausgangsstoffe gegebenenfalls von der Verwendung ausgeschlossen.
Müssen Ausgangsstoffe umgefüllt werden, darf deren Reinheitsgrad dabei nicht beeinträchtigt werden. Die Lagerung der Ausgangsstoffe darf nur in Räumen erfolgen, die 
in ordentlichen und sauberem Zustand sind. Über die notwendigen Reinigungsmaßnahmen ist ein Nachweis zu führen. Die zur Lagerung benutzten Räume dürfen nicht für andere, produktionsfremde Zwecke genutzt werden und es dürfen keine Durchgangsräume sein. 
Die Ausgangsstoffe müssen nach den jeweils gültigen TGL angegebenen Aufbewahrungsbedingungen gelagert werden. Dabei muß die Raumtemperatur und Luftfreuchtigkeit der Lagerräume täglich kontrolliert und registriert werden. Die Stabilität der Ausgangsstoffe darf durch die Lagerung nicht beeinträchtigt werden. 

=== Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen

Hinsichtlich des erfoderlichen Reinheitsgrades der Produktionsräume werden die Reinheitsstufen 1 bis 4 unterschieden. 
Die Reinheitsstufen der Räume werden durch unterschiedliche Farbgebung deutlich sichtbar gekennzeichnet:

"Reinheitsstufe 1a" und "Reinheitsstufe 1b":: rot gekennzeichnet
"Reinheitsstufe 2":: blau gekennzeichnet
"Reinheitsstufe 3":: grün gekennzeichnet
"Reinheitsstufe 4":: gelb gekennzeichnet

Diese Sicherheitsfarben erfolgen nach TGL - Normen. 

=== Richtlinien für die entsprechenden Produktionsräume

Abgesehen von den bereits genannten Bestimmungen für die Kennzeichnung der Produktionsräume durch Sicherheitsfarben sind weitere Kriterien zu beachten. Auf einige der wichtigsten will ich in meinen Ausführungen eingehen.

Der Reinheitsgrad von Personen und Materialien ist durch das Passieren von Schleusen von einer geringeren in die jeweils erforderliche höhere Reinheitsstufe zu heben.
Dabei sind für Produktionsräume mit Reinheitsstufen 1b - 3 voneinander getrennte Personen- und Materialschleusen erforderlich. Bei den Personenschleusen unterscheiden wir je nach Reinheitsstufen Doppelschleusen und Einfachschleusen. 

Doppelschleusen werden vor Produktionsräumen der Reinheitsstufen 1b und 2 benutzt. Sie bestehen aus einer Vorschleuse und einer Sterilschleuse. In der Vorschleuse wird die Wegekleidung abgelegt und in der Sterilschleuse,
die Sterilkleidung angelegt. In der jewiligen Schleuse müssen Aufbewahrungsmöglichkeiten für die Bekleidungen sein. Außerdem muß die Möglichkeit der gründlichen Reinigung und Desinfektion der Hände und Unterarme bestehen. Vor Produktionsräumen der Reinheitsstufe 3 sind Einfachschleusen vorhanden. Hier wird die Wegekleidung abgelegt und die Hygienekleidung angelegt.

Materialien, die in die Produktionsräume einzuschleusen sind, werden durch Materialschleusen befördert. Hier wird durch geeignete Methoden, die hygienische Reinigung durchgeführt, zum Beispiel durch Entfernung des Verpackungsmaterials, der Desinfektion der Verpackung, durch Besprühen, Begasung oder durch UV-Strahler. 

Weitere Anforderungen, die an Produktionsräume für Antibiotika gestellt werden:

- Die Räume müssen in sauberem und ordentlichen Zustand gehalten werden. Sie müssen in ihrer Größe eine entsprechende Reinigung und Wartung der Maschinen zulassen.
- Das Aufbewahren von persönlichen Gegenständen soweie das Halten von Zimmerpflanzen und Tieren ist nicht zulässig.
- Wände, Decken und Fußböden sowie Arbeitsflächen müssen eine glatte Oberfläche auweisen und für Desinfektionsmittel geeignet sein, je nach Reinheitsstufen gelten noch spezielle Hinweise. 
- Ablfußwasser müssen ungehindert abfließen können und eine Desinfektion möglich sein
- je nach Reinheitsstufen müssen die Türen und Fenster dicht verschließbar sein und während des Produktionsprozesses geschlossen gehalten werden.
- Belüftungs- und Klimaanlagen müssen eine gute Luftzirkulation aufwweisen und vermeiden das Verunreinigungen der Produktionsräume auftreten
- Räume für mit Stauentwicklung verbundenen Arbeiten müssen eine wirksame Absaugvorrichtung haben
- je nach Reinheitsstufen ist auf entsprechende Temperaturen und Einhaltung der relativen Luftfeutigkeit zu achten
- die zum Waschen und Desinfizieren der Hände benötigten Wasserhähne müssen in den Produktionsräumen mit Arm- und Fußhebel bedienbar sein.
- Toiletten dürfen keinen direkten Zugang zu den Produktionsräumen haben
- die Säuberung der Produktionsräume und der sanitären Einrichtungen sind nach betrieblichen Arbeitsvorschriften regelmäßig durchzuführen; über die Art der verwendeten Desinfektionsmittel ist ein schriftlicher Nachweis zu führen



