== Zur Einhaltung der RHR Richtlinien im Bereich Antibiotika

In der DDR sind Normen für die mikrobilogische Reinheit von Arzneimitteln mit dem 1977 erfolgten Inkrafttreten des Arzneibuches der DDR verbindlich geworden. 
Beratungen über die Ausarbeitung einer Rahmen-Hygiene-Richtlinie für die Produktion von Arzneimitteln und Gesundheitspflegemitteln begannen in der DDR im Jahr 1973.
Die zur Zeit bestehende Fassung der Rahmenhygieneordnung besitzt noch keine gesetzliche Verbindlichkeit, sondern sie stellt lediglich eine Empfehlung dar. 
Aus den RHR ergeben sich folgnde Kriterien:

1. Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial
2. Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen
3. Richtlinien für die entsprechenden Produktionsräume
4. Richtlinien für Ausrüstung und Verfahren
5. Richtlinien für Personen, die in diesem Bereich der Herstellung von Antibiotika arbeiten
6. Richtlinien für betriebliche Kontrollen durch verschiedene Verfahren

=== Richtlinien für die Ausgangsstoffe und für das Verpackungsmaterial

Hierunter ist die mikrobiologische Reinheit der Ausgangsstoffe zu verstehen.  Der Hersteller von Arzenimitteln ist verpflichtet, sich bei den Herstellern bzw. Lieferanten der Ausgangsstoffe über bereits durchgführte Maßnahmen dieser Art zu informieren. Der Lieferant ist gleichzeitig verpflichtet, eine entsprechende Dokumentation zu übergeben. 

Das Verpackungsmaterial muß so beschaffen sein, daß eine Kontaminiation der Ausgangsstoffe vermieden wird. 
Sind die Verpackunge der Ausgangsstoffe beschädigt, verschmutzt oder durchfeutet, so werden die Ausgangsstoffe gegebenenfalls von der Verwendung ausgeschlossen.
Müssen Ausgangsstoffe umgefüllt werden, darf deren Reinheitsgrad debei nicht beeinträchtigt werden. Die Lagerung der Ausgangsstoffe darf nur in Räumen erfolgen, die 
in ordentlichen fund sauberem Zustand sind. Über die notwendigen
Reinigungsmaßnahmen ist ein Nachweis zu führen. Die zur fLagerun benutzten Räume dürfen nicht für andere, produktionsfremde Zwecke genutzt werden
und es dürfen keine Durchgangsräume sein. Die Ausgangsstoffe
müssen nach den jeweils gültigen TGL angegebenen Aufbewahrungsbedingungen gelagert werden. Dabei muß die Raumtemperatur und Luftfreuchtigkeit der Lagerräume täglich 
kontrolliert und registriert werden. Die Stabilität der Ausgangsstoffe darf durch die Lagerung nicht beeinträchtigt werden. 

=== Richtlinien hinsichtlich der Einteilung nach Reinheitsstufen

Hinsichtlich des erfoderlichen Reinheitsgrades der Produktionsräume werden die Reinheitsstufen 1 bis 4 unterschieden. 
Die Reinheitsstufen der Räume werden durch unterschiedliche Farbgebung deutlich sichtbar gekennzeichnet:

"Reinheitsstufe 1a" und "Reinheitsstufe 1b":: rot gekennzeichnet
"Reinheitsstufe 2":: blau gekennzeichnet
"Reinheitsstufe 3":: grün gekennzeichnet
"Reinheitsstufe 4":: gelb gekennzeichnet

Diese Sicherheitsfarben erfolgen nach TGL - Normen. 




