== Spezielle Richtlinien für die Abteilung Antibiotika in der PA5

In der Abteilung PA 5 Bereich Antibiotika mit:

- der Abfüllung = Reinheitsstufe 1b
- dem Mahlraum = Reinheitsstufe 1b
- dem Gummistopfenraum = Reinheitsstufe 3
- dem Spülraum = Reinheitsstufe 3
- dem Tunnel = Reinheitsstufe 3

und der Ölvorbereitung gelten folgende Richtlinien nach der RHR.

[underline]#Reinheitsstufe 1b für Abfüllraum und Mahlraum# 

. Produktionsraum:
sterilbelüftete Räume, Fenster und Türen müssen dicht verschließbar sein und währed des Produktonsprozesses geschlossen gehalten werden. Wände, Decken, Fußböden und Arbeitsflächen müssen glatte Oberflächen aufweisen zwecks staubbindender Reinigung und Desinfektion.
Die Raumtemperatur darf 26°C nicht übersteigen. 
Die Luftfeuchtigkeit sollte 40% bis 60% betragen. 
Ein Überdruck von 15 Pa muß vorhanden sein.
Der Fußboden muß fugenlos und gekehlt sein.
. Schleusen:
** voneinander getrennte Personen- und Meterialschleusen (Doppelschleusen) sind nötig
** Möglichkeit muß vorhanden sein, in der Schleuse die Hände zu waschen und zu desinfizieren
. Häufigkeit der Desinfektions- und Reinigungsmaßnahmen
** Fußböden müssen täglich gereinigt und desinfziert werden
** Wände mindestens monatlich reinigen und desinfizieren
** Türen wöchentlich reinigen und desinfizieren
** Türgriffe täglich reinigen und desinfizieren
** Fenster vierteljährlich reinigen
** Fensterbretter täglich reinigen und desinfizieren
** Beleuchtungskörper und UV-Strahler vierteljährlich reinigen und desinfizieren
** Stühle täglich reinigen und desinfizieren
** Schränke (außen) wöchentlich reinigen und desinfizieren
. Personen
** vor Arbeitsbeginn Hände und Unterarme waschen und anschließend desinfizieren mit Wofasept
** Verwendung sterilisierter flüssiger Seife
** Verwendung einer Nagelbürste zur Händereinigung
** es müssen sterile Einmalgebrauchtshandtücher verwendet werden, die anschließend in verschließbare, täglich zu desinfizierende Behälter geworfen werden oder man verwendet ein Trockengerät
** Schmuckgegenstände oder Armbanduhren sind unzulässig
** es muß eine Reinraumkleidung aus fusselarmen Geweben und ein Wegekittel zur Verfügung stehen, die Kleidung muß täglich nach jeder Schicht gewechselt werden
** sterilisierte Arbeitsstrümpfe müssen vorhanden sein und täglich gewechselt werden
** saubere Arbeitsschuhe ebenfalls
** keine Nasenreinigung im aseptischen Bereich
** zu Boden gefallene Materialien nicht weiter verarbeiten
** ein sterilisierter Kopf- und Mundschutz ist nötig der täglich gewechselt wird bzw. Mundschutz öfter
** bei Bedarf sind sterilisierte und desinfizierte Gummihandschuhe zu benutzen
** Essen, Trinken und Rauchen ist im Produktionsraum nicht gestattet

[underline]#In den Produktionsräumen mit der Reinheiststufe 3 treffen folgende Richtlinien zu:# 

. Produktionsraum:
** Wände, Fußböden und Arbeitsflächen müssen glatte Oberflächen aufweisen
** Fußböden sollen fugenlos sein und dürfen keine Unebenheiten aufweisen
** Fenster und Türen müssen dicht verschließbar sein und während des Produktionsprozesses geschlossen gehalten werden
** Raumtemperatur darf nicht über 26°C steigen
** Luftfeuchtigkeit sollte 40% bis 60% betragen
. Schleusen:
** voneinander getrennte Personenn- und Materialschleusen, in den Personenschleusen werden Wegekleidung (Kittel, Schuhe ab- und die Hygienekleidung angelegt - diese Richtlinie müßte in der PA 5 Antibiotika noch realisiert werden. 
. Häufigkeit der Desinfektions- und Reinigungsmaßnahmen:
** Fußböden müssen täglich gereinigt und wöchentlich desinfiziert werden
** Wände mindestens vierteljährlich reinigen und desinfizieren
** Türen und Türgriffe wöchentlich reinigen und desinfizieren
** Fenster vierteljährlich reinigen
** Fensterbretter wöchentlich reinigen und desinfizieren
** Bleuchtugnskörper und UV-Strahler halbjährlich reinigen und desinfizieren
** Stühle und Schränke (außen) monatlich reinigen und desinfizieren
. Personen
** vor Arbeitsbeginn Hände waschen
** Verwendung sterilisierter Seife und einer Nagelbürste zur Händereinigung
** anschließend Händedesinfektion
** Benutzen von Einmalgebrauchshandtüchern oder Trockengeräten
** Schmuckgegenstände an Händen und Unterarmen sind unzulässig
** als Arbeitsbekleidung ist ein Kittel zu benutzen, der zweimal wöchentlich gewechselt wird
** saubere Arbeitsschuhe
** Kopfschutz (z.B. OP-Mütze) der rutschfest ist und zweimal wöchentlich gewechselt wird
** Essen, Trinken und Rauchen ist in Produktionsräumen nicht gestattet

[underline]#Quellennachweis# 

. Rahmen-Hygiene-Reichtlinien für die Produktion von Arzneimitteln und Gesundheitspflegemitteln (RHR), Fassung 1980, Sonderdruck aus "Zbl. Pharm." 121 (1982) Heft 1
. R. Voigt, Lehrbuch der pharmazeutischen Technologie, Verlag "Vok und Wissen" Berlin 1979, 3. überarbeitete Auflage
. Helga Schröder, Mikrobiologisches Praktikum, Verlag "Volk und Wissen" Berlin 1980, 3. Auflage
. Arbeitsvorschrift "Leutoxieren von Substanzen"
. Arzneimittelbuch der DDR, 2. Auflage

[underline]#Erklärung#

Hiermit erkläre ich, daß ich die Hausarbeit selbständig angefertigt und nur die im Quellennachweis angegebene Literatur verwendet habe. 

Bernburg, April 1987                                      Thomas Michel
